dist: jammy
language: python
matrix:
  include:
    - python: 3.9
    - python: 3.11
cache: pip
install:
  - python --version
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt

  - pwd
  - cd ..
  - git clone https://github.com/hubmapconsortium/ingest-validation-tools.git
  - cd ingest-validation-tools
  - pwd
  - git checkout $(git describe --tags $(git rev-list --tags --max-count=1)) # check out latest tagged release

  - cd ../ingest-validation-tests # Not sure if this is required, or if it resets between sections.
script:
  - ./test.sh
