language: python
python:
  - "3.9"
cache: pip
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt

  - pwd
  - cd ..
  - git clone https://github.com/hubmapconsortium/ingest-validation-tools.git
  - cd ingest-validation-tools
  - pwd
  # - git checkout $(git describe --tags $(git rev-list --tags --max-count=1)) # check out latest tagged release
  - git checkout main
  - pip install -r requirements.txt # install dependencies from ingest-validation-tools
script:
  - ./test.sh
