language: python
python:
  - '3.7'
cache: pip
install:
  - pip install -r requirements.txt
  # - pip install -r requirements-dev.txt
  - cd ..
  - git clone https://github.com/hubmapconsortium/ingest-validation-tools.git
  - cd ingest-validation-tools
  - git checkout v0.0.5
  - pip install -r requirements.txt
  - cd ../../ingest-validation-tests # Not sure if this is required, or if it resets between sections.
script:
  - ./test.sh
