language: python
python:
  - '3.7'
cache: pip
install:
  - pip install -r requirements.txt
  # - pip install -r requirements-dev.txt
  - cd ..
  - git clone https://github.com/hubmapconsortium/ingest-validation-tools.git
  - git checkout v0.0.5
  - pip install -r requirements.txt
  - cd -
script:
  - ./test.sh
