name: Tests

on: [push, pull_request]

jobs:
  build:

    # Available versions:
    # https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: '3.6' # The Red Hat version used by IEC doesn't support anything more recent. :(
        architecture: 'x64'

    - run: |
      pip install -r requirements.txt
      cd ..
      git clone https://github.com/hubmapconsortium/ingest-validation-tools.git
      cd ingest-validation-tools
      git checkout v0.0.5
      pip install -r requirements.txt
    
      cd ../ingest-validation-tests
      ./test.sh 
