name: Run isort
on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: isort/isort-action@v1
        with:
          configuration: "--profile black"
          requirements-files: "requirements.txt requirements-dev.txt"
