name: Run isort
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - uses: isort/isort-action@master
        with:
          configuration: "--check-only --diff --profile black --multi-line 3"
          requirementsFiles: "requirements.txt requirements-test.txt"
